# Generated by Django 3.1.6 on 2021-03-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pribor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.lpu')),
            ],
        ),
        migrations.CreateModel(
            name='kadri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.lpu')),
            ],
        ),
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.lpu')),
            ],
        ),
    ]
