# Generated by Django 3.1.6 on 2021-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_spr_dinam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insultik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vozrast', models.IntegerField()),
                ('gip', models.IntegerField()),
                ('heart', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('pol', models.IntegerField()),
                ('work', models.IntegerField()),
                ('pro', models.IntegerField()),
                ('sax', models.FloatField()),
                ('kuru', models.IntegerField()),
                ('rost', models.FloatField()),
                ('ves', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='auto',
            name='lpu',
        ),
        migrations.RemoveField(
            model_name='kadri',
            name='lpu',
        ),
        migrations.DeleteModel(
            name='mkb10',
        ),
        migrations.DeleteModel(
            name='patient',
        ),
        migrations.DeleteModel(
            name='persons_for_cons',
        ),
        migrations.RemoveField(
            model_name='pribor',
            name='lpu',
        ),
        migrations.DeleteModel(
            name='spr_dinam',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lpu_u',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='auto',
        ),
        migrations.DeleteModel(
            name='kadri',
        ),
        migrations.DeleteModel(
            name='lpu',
        ),
        migrations.DeleteModel(
            name='pribor',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
