# Generated by Django 3.1.6 on 2021-05-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210518_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='insultik',
            name='rezult',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
