# Generated by Django 3.1.6 on 2021-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210518_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='insultik',
            name='use',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
