# Generated by Django 3.1.6 on 2021-06-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_lpubd_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
