# Generated by Django 3.1.6 on 2021-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20210609_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_list_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
