# Generated by Django 3.1.6 on 2021-07-06 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_profile_is_list_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(default='NONE', max_length=150)),
                ('i', models.CharField(default='NONE', max_length=150)),
                ('o', models.CharField(default='NONE', max_length=150)),
                ('dr', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(default='NONE', max_length=150)),
                ('polis', models.CharField(default='NONE', max_length=150)),
                ('snils', models.CharField(default='NONE', max_length=150)),
                ('telrod', models.CharField(default='NONE', max_length=150)),
            ],
        ),
    ]
