# Generated by Django 3.1.6 on 2021-07-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_case_doctor_fromlpu_srmp_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='tolpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(default='NONE', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='dostavlen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedost', models.DateTimeField(default='datetime.now')),
                ('timepriem', models.DateTimeField(default='datetime.now')),
                ('doctor', models.CharField(default='NONE', max_length=150)),
                ('primech', models.CharField(default='NONE', max_length=150)),
                ('tolpu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tolpu_s', to='hospital.tolpu')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='todost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dostavlen_s', to='hospital.dostavlen'),
        ),
    ]
