# Generated by Django 3.1.6 on 2021-07-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_after_atributes_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='intime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default='datetime.now')),
                ('val_int', models.IntegerField()),
                ('val_float', models.FloatField()),
                ('val_text', models.CharField(default='NONE', max_length=150)),
                ('groupid', models.IntegerField()),
                ('atrib', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.atributes')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.case')),
            ],
        ),
    ]
