# Generated by Django 3.1.6 on 2021-07-27 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0017_intime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='id_doct',
        ),
        migrations.AddField(
            model_name='case',
            name='id_vrach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='id_trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.transport'),
        ),
    ]
