# Generated by Django 3.1.6 on 2021-07-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20210727_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
