# Generated by Django 3.1.6 on 2021-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
