# Generated by Django 3.1.6 on 2021-08-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_case_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='id_srmp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.srmp'),
            preserve_default=False,
        ),
    ]
