# Generated by Django 3.1.6 on 2021-08-02 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_case_id_srmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='case',
            name='dateti',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='case',
            name='dscons',
            field=models.CharField(default='X00.X', max_length=150),
        ),
        migrations.AlterField(
            model_name='case',
            name='dslpu',
            field=models.CharField(default='X00.X', max_length=150),
        ),
        migrations.AlterField(
            model_name='case',
            name='vzyat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
