# Generated by Django 3.1.6 on 2021-08-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20210803_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fromlpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.fromlpu'),
            preserve_default=False,
        ),
    ]
