# Generated by Django 3.1.6 on 2021-08-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_remove_before_val_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='after',
            name='val_int',
        ),
        migrations.RemoveField(
            model_name='intime',
            name='val_int',
        ),
    ]
