# Generated by Django 3.1.6 on 2021-08-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_atributes_potomok'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributes',
            name='fortab',
            field=models.CharField(default='before,after,intime', max_length=150),
        ),
    ]
