# Generated by Django 3.1.6 on 2021-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_atributes_fortab'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributes',
            name='papka',
            field=models.CharField(default='obsh', max_length=150),
        ),
    ]
