# Generated by Django 3.1.6 on 2021-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_atributes_papka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributes',
            name='groupid',
        ),
        migrations.RemoveField(
            model_name='atributes',
            name='papka',
        ),
        migrations.RemoveField(
            model_name='atributes',
            name='potomok',
        ),
        migrations.AddField(
            model_name='atributes',
            name='ispotomok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atributes',
            name='roditel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atributes',
            name='root',
            field=models.IntegerField(default=0),
        ),
    ]
