# Generated by Django 3.1.6 on 2021-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_atributes_potomki'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributes',
            name='umolch',
            field=models.CharField(default='', max_length=150),
        ),
    ]
