# Generated by Django 3.1.6 on 2021-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_auto_20210813_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='before',
            name='groupid',
        ),
        migrations.AddField(
            model_name='before',
            name='valtype',
            field=models.IntegerField(default=0),
        ),
    ]
