# Generated by Django 3.1.6 on 2021-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_auto_20210813_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='before',
            name='val_float',
            field=models.FloatField(default=-1000.0),
        ),
        migrations.AlterField(
            model_name='before',
            name='val_text',
            field=models.CharField(default='NOT_VAL', max_length=150),
        ),
    ]
