# Generated by Django 3.1.6 on 2021-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_auto_20210813_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='vputi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='vzyat',
            field=models.DateTimeField(blank=True),
        ),
    ]
