# Generated by Django 3.1.6 on 2021-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_auto_20210814_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='vzyat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
