# Generated by Django 3.1.6 on 2021-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_auto_20210814_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intime',
            name='groupid',
        ),
        migrations.AddField(
            model_name='intime',
            name='valtype',
            field=models.IntegerField(default=0),
        ),
    ]
