# Generated by Django 3.1.6 on 2021-08-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_auto_20210816_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intime',
            name='val_float',
            field=models.FloatField(blank=True),
        ),
    ]
