# Generated by Django 3.1.6 on 2021-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_auto_20210827_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intime',
            name='val_float',
            field=models.FloatField(default=-1000.0),
        ),
    ]
