# Generated by Django 3.1.6 on 2021-08-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0040_remove_intime_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intime',
            name='time',
        ),
        migrations.CreateModel(
            name='intimetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default='datetime.now')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.case')),
            ],
        ),
        migrations.AddField(
            model_name='intime',
            name='intimetime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.intimetime'),
            preserve_default=False,
        ),
    ]
