# Generated by Django 3.1.6 on 2021-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0041_auto_20210827_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='after',
            name='groupid',
        ),
        migrations.AlterField(
            model_name='after',
            name='val_float',
            field=models.FloatField(default=-1000.0),
        ),
    ]
