# Generated by Django 3.1.6 on 2021-08-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0042_auto_20210827_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dostavlen',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='dostavlen',
            name='tolpu',
        ),
        migrations.AddField(
            model_name='dostavlen',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.case'),
            preserve_default=False,
        ),
    ]
