# Generated by Django 3.1.6 on 2021-08-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0043_auto_20210829_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='todost',
        ),
    ]
