# Generated by Django 3.1.6 on 2021-08-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0045_profile_is_commit_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tolpu',
        ),
    ]
