# Generated by Django 3.1.6 on 2021-09-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0048_auto_20210921_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostavlen',
            name='lpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.lpubd'),
        ),
    ]
