# Generated by Django 3.1.6 on 2021-09-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0054_deadinroad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadinroad',
            name='valtype',
        ),
    ]
