# Generated by Django 3.1.6 on 2021-11-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0058_auto_20211128_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='fromlpu',
            name='rast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fromlpu',
            name='roadoc',
            field=models.IntegerField(default=0),
        ),
    ]
