# Generated by Django 3.1.6 on 2022-01-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0060_atributes_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fromlpu',
            name='rast',
        ),
        migrations.RemoveField(
            model_name='fromlpu',
            name='roadoc',
        ),
        migrations.RemoveField(
            model_name='fromlpu',
            name='roadrate',
        ),
    ]
