# Generated by Django 3.1.6 on 2022-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0061_auto_20220130_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='roadoc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='roadrate',
            field=models.FloatField(default=0),
        ),
    ]
