# Generated by Django 3.1.6 on 2022-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0062_auto_20220130_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lpudost',
            field=models.IntegerField(default=0),
        ),
    ]
